[project]
name = "generate-3d-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "flask-jwt-extended>=4.7.4",
    "flask-openapi3[elements,rapidoc,rapipdf,redoc,scalar,swagger]>=4.3.2",
    "openai>=2.38.0",
    "pwdlib[argon2]>=0.3.0",
    "redis>=7.4.0",
    "sqlalchemy>=2.0.49",
]
